name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        apt update
        apt install lynx youtube-dl -y
        ./cda-dl.sh 
