name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        dir
        sudo apt update
        sudo apt install lynx youtube-dl -y
    - name: Test
      run: |
        chmod +x cda_dl.sh
        ./cda_dl.sh 
